# Configuración del servidor
server.port=8080
server.servlet.context-path=

# Configuración de la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sigs_cementerio?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar cache de Thymeleaf en desarrollo
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# Habilitar logging detallado para Spring Security en caso de ser necesario
# logging.level.org.springframework.security=DEBUG
